# Generated by Django 4.0.5 on 2022-06-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AusstiegAmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schriftlichepruefung', models.DateTimeField(default=django.utils.timezone.now)),
                ('muendlichepruefung', models.DateTimeField(default=django.utils.timezone.now)),
                ('akten_abgegeben', models.DateTimeField(default=django.utils.timezone.now)),
                ('therapeutenornder_fertiggestellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('festplatte_abgegeben', models.DateTimeField(default=django.utils.timezone.now)),
                ('schluessel_abgegeben', models.DateTimeField(default=django.utils.timezone.now)),
                ('schließfach_geprueft', models.DateTimeField(default=django.utils.timezone.now)),
                ('tuerchip_abgegeben', models.DateTimeField(default=django.utils.timezone.now)),
                ('tuerschild_abgegeben', models.DateTimeField(default=django.utils.timezone.now)),
                ('namensschild_abgegeben', models.DateTimeField(default=django.utils.timezone.now)),
                ('versicherung_abgemeldet', models.DateTimeField(default=django.utils.timezone.now)),
                ('fachkonverenz_ausgetragen', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_verteilerlisten_entfernt', models.DateTimeField(default=django.utils.timezone.now)),
                ('dauerbuchung_geloescht', models.DateTimeField(default=django.utils.timezone.now)),
                ('Staatspruefungstermine_eingetragen', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fiona_auf_beendet', models.DateTimeField(default=django.utils.timezone.now)),
                ('festplatte_geloescht', models.DateTimeField(default=django.utils.timezone.now)),
                ('pc_account_deaktiviert', models.DateTimeField(default=django.utils.timezone.now)),
                ('pia_zugang_deaktiviert', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_gelöscht', models.DateTimeField(default=django.utils.timezone.now)),
                ('vorname', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
